crew_name: "Generate Story Crew"
usecase: "Generate Story"
module_name: "generate_story"

crews:
  generate_story_crew:

    input:
      - key_name: "brd_content"
        source: "file"
        path: "data/knowledge/example/project_brd.md"
        format: "text"
       
    steps:
      - task_file: "data/crew/Generate Story/tasks/generate_story_map_task.yaml"
        agent_file: "data/crew/Generate Story/agents/backlog_cartographer_agent.yaml"

pipeline:
  - "generate_story_crew"


