
domain_root_path: "D:/Crew/bala-katha/data/story"
output_dir_path: "D:/Crew/bala-katha/.Amsha/output/intermediate"
dvc_output_dir: "D:/Crew/bala-katha/.Amsha/output/"
commit_message: "data: setup dvc and seed plot"
google_drive:
  folder_id: "id"
  gdrive_client_id: "gdrive_client_id"
  gdrive_client_secret: "gdrive_client_secret"


  
  
